
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoservis.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Adresa
{

    public string Naziv { get; set; }

    public string KucniBroj { get; set; }

    public int MjestoIdMjesto { get; set; }

    public int IdAdresa { get; set; }



    public virtual Mjesto Mjesto { get; set; }

}

}
