//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoservisDATAContainer : DbContext
    {
        public AutoservisDATAContainer()
            : base("name=AutoservisDATAContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klijent> KlijentSet { get; set; }
        public virtual DbSet<Mjesto> MjestoSet { get; set; }
        public virtual DbSet<Adresa> AdresaSet { get; set; }
        public virtual DbSet<Vozilo> VoziloSet { get; set; }
        public virtual DbSet<TerminPregleda> TerminPregledaSet { get; set; }
        public virtual DbSet<Zaposlenik> ZaposlenikSet { get; set; }
        public virtual DbSet<ObradaVozila> ObradaVozilaSet { get; set; }
        public virtual DbSet<Racun> RacunSet { get; set; }
        public virtual DbSet<Usluga> UslugaSet { get; set; }
        public virtual DbSet<RezervniDio> RezervniDioSet { get; set; }
        public virtual DbSet<Dobavljac> DobavljacSet { get; set; }
        public virtual DbSet<Katalog> KatalogSet { get; set; }
        public virtual DbSet<Narudzba> NarudzbaSet { get; set; }
        public virtual DbSet<StavkaNarudzba> StavkaNarudzbaSet { get; set; }
        public virtual DbSet<ZahtjevZaNarudzbom> ZahtjevZaNarudzbomSet { get; set; }
        public virtual DbSet<ZahtjevZaNarudzbomStavka> ZahtjevZaNarudzbomStavkaSet { get; set; }
        public virtual DbSet<RacunStavka> RacunStavkaSet { get; set; }
    }
}
