
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoservis.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TerminPregleda
{

    public System.DateTime DatumIVrijeme { get; set; }

    public int VoziloIdVozilo { get; set; }

    public int KlijentIdKlijent { get; set; }

    public int Status { get; set; }

    public int Id { get; set; }



    public virtual Vozilo Vozilo { get; set; }

    public virtual Klijent Klijent { get; set; }

}

}
