
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoservis.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Vozilo
{

    public Vozilo()
    {

        this.ObradaVozila = new HashSet<ObradaVozila>();

    }


    public int IdVozilo { get; set; }

    public string Marka { get; set; }

    public string Tip { get; set; }

    public short GodinaProizvodnje { get; set; }



    public virtual ICollection<ObradaVozila> ObradaVozila { get; set; }

    public virtual Klijent Klijent { get; set; }

}

}
