//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoservisDATAContainer : DbContext
    {
        public AutoservisDATAContainer(string connectionString)
           : base("name=" + connectionString)

        {

        }

        public AutoservisDATAContainer(DbConnection connection)
            : base(connection, false)
        {
        }

        /*  protected override void OnModelCreating(DbModelBuilder modelBuilder)
          {
              throw new UnintentionalCodeFirstException();
          }*/

        public DbSet<Klijent> KlijentSet { get; set; }
        public DbSet<Mjesto> MjestoSet { get; set; }
        public DbSet<Adresa> AdresaSet { get; set; }
        public DbSet<Vozilo> VoziloSet { get; set; }
        public DbSet<TerminPregleda> TerminPregledaSet { get; set; }
        public DbSet<Zaposlenik> ZaposlenikSet { get; set; }
        public DbSet<ObradaVozila> ObradaVozilaSet { get; set; }
        public DbSet<Racun> RacunSet { get; set; }
        public DbSet<Usluga> UslugaSet { get; set; }
        public DbSet<RezervniDio> RezervniDioSet { get; set; }
        public DbSet<Dobavljac> DobavljacSet { get; set; }
        public DbSet<Katalog> KatalogSet { get; set; }
        public DbSet<Narudzba> NarudzbaSet { get; set; }
        public DbSet<StavkaNarudzba> StavkaNarudzbaSet { get; set; }
        public DbSet<ZahtjevZaNarudzbom> ZahtjevZaNarudzbomSet { get; set; }
        public DbSet<ZahtjevZaNarudzbomStavka> ZahtjevZaNarudzbomStavkaSet { get; set; }
        public DbSet<RacunStavka> RacunStavkaSet { get; set; }
        public DbSet<ZaposlenikObrada> ZaposlenikObradaSet { get; set; }
    }
}
