//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dobavljac
    {
        public int IdDobavljac { get; set; }
        public string Naziv { get; set; }
        public int AdresaIdAdresa { get; set; }
    
        public virtual Adresa Adresa { get; set; }
    }
}
