//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klijent
    {
        public Klijent()
        {
            this.Vozilo = new HashSet<Vozilo>();
        }
    
        public int IdKlijent { get; set; }
        public string Prezime { get; set; }
        public string Ime { get; set; }
        public string Lozinka { get; set; }
        public int AdresaIdAdresa { get; set; }
    
        public virtual ICollection<Vozilo> Vozilo { get; set; }
        public virtual Adresa Adresa { get; set; }
    }
}
