//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        public Narudzba()
        {
            this.StavkaNarudzba = new HashSet<StavkaNarudzba>();
        }
    
        public int IdNarudzba { get; set; }
        public int VoditeljIdVoditelj { get; set; }
        public System.DateTime DatumNarudzbe { get; set; }
        public int ZaposlenikIdZaposlenik { get; set; }
    
        public virtual ICollection<StavkaNarudzba> StavkaNarudzba { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
