//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObradaVozila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObradaVozila()
        {
            this.Mehanicari = new HashSet<Mehanicar>();
        }
    
        public int IdObrada { get; set; }
        public System.DateTime DatumIVrijemeZaprimanja { get; set; }
        public Nullable<System.DateTime> DatumIVrijemePreuzimanja { get; set; }
        public string Opis { get; set; }
        public int VoziloIdVozilo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mehanicar> Mehanicari { get; set; }
        public virtual Vozilo Vozilo { get; set; }
        public virtual Racun Racun { get; set; }
    }
}
