//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public Racun()
        {
            this.RacunStavka = new HashSet<RacunStavka>();
        }
    
        public int IdRacun { get; set; }
        public Nullable<System.DateTime> DatumIzdavanja { get; set; }
        public decimal Iznos { get; set; }
        public int KlijentIdKlijent { get; set; }
        public int ZaposlenikIdZaposlenik { get; set; }
    
        public virtual ICollection<RacunStavka> RacunStavka { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
