//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservis.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.RacunStavka = new HashSet<RacunStavka>();
        }
    
        public int IdRacun { get; set; }
        public Nullable<System.DateTime> DatumIzdavanja { get; set; }
        public decimal Iznos { get; set; }
        public int KlijentIdKlijent { get; set; }
        public int MehanicarIdMehanicar { get; set; }
    
        public virtual Mehanicar Mehanicar { get; set; }
        public virtual ObradaVozila ObradaVozila { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RacunStavka> RacunStavka { get; set; }
    }
}
