
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoservis.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class RacunStavka
{

    public int RacunIdRacun { get; set; }

    public int UslugaIdUsluga { get; set; }

    public int Kolicina { get; set; }

    public decimal Cijena { get; set; }



    public virtual Racun Racun { get; set; }

    public virtual Usluga Usluga { get; set; }

}

}
