
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoservis.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class RezervniDio
{

    public RezervniDio()
    {

        this.StavkaNarudzba = new HashSet<StavkaNarudzba>();

    }


    public int IdRezervniDio { get; set; }

    public string Naziv { get; set; }

    public string Opis { get; set; }

    public decimal Cijena { get; set; }

    public int DostupnaKolicina { get; set; }



    public virtual ICollection<StavkaNarudzba> StavkaNarudzba { get; set; }

}

}
