
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoservis.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ZahtjevZaNarudzbom
{

    public ZahtjevZaNarudzbom()
    {

        this.ZahtjevZaNarudzbomStavka = new HashSet<ZahtjevZaNarudzbomStavka>();

    }


    public int Id { get; set; }

    public int MehanicarIdMehanicar { get; set; }

    public System.DateTime Datum { get; set; }

    public int ZaposlenikIdZaposlenik { get; set; }



    public virtual ICollection<ZahtjevZaNarudzbomStavka> ZahtjevZaNarudzbomStavka { get; set; }

    public virtual Zaposlenik Zaposlenik { get; set; }

}

}
