
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoservis.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Zaposlenik
{

    public Zaposlenik()
    {

        this.ZaposlenikObrade = new HashSet<ZaposlenikObrada>();

    }


    public int IdZaposlenik { get; set; }

    public string Prezime { get; set; }

    public string Ime { get; set; }

    public System.DateTime DatumZaposlenja { get; set; }



    public virtual Adresa IdAdresa { get; set; }

    public virtual ICollection<ZaposlenikObrada> ZaposlenikObrade { get; set; }

}

}
